services:
  - type: web
    name: medibook-frontend
    runtime: node
    plan: starter
    repo: https://github.com/chauhansahab25/MediBook-Frontend.git
    rootDir: medibook-frontend
    buildCommand: "npm ci && npm run build --prod"
    startCommand: "npx http-server dist/medibook-frontend -p $PORT -C --gzip"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://medibook-onlineappointmentbookingsystem.onrender.com/api/v1
